app:
  name: x-users
  user_cookie: c_user
server:
  port: 1234
jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN
spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://localhost/myDatabase
#    username: myUser
#    password: myPassword
#    driver-class-name: com.mysql.jdbc.Driver

